version: '3.4'

services:
  catalogdb:
    image: postgres:latest
    container_name: catalogdb 
    environment:
      POSTGRES_DB: "CatalogDatabase"
      POSTGRES_USER: "VladPostgres"
      POSTGRES_PASSWORD: "VladPostgres"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
        
  usercarddb:
    image: postgres:latest
    container_name: usercarddb
    environment:
      POSTGRES_DB: "UsercardDatabase"
      POSTGRES_USER: "VladPostgres"
      POSTGRES_PASSWORD: "VladPostgres"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"

  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: always
    ports:
        - "6379:6379"
          
  userdb:
    image: postgres:latest
    container_name: userdb
    environment:
      POSTGRES_DB: "UserDatabase"
      POSTGRES_USER: "VladPostgres"
      POSTGRES_PASSWORD: "VladPostgres"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
        - "5435:5432"

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    container_name: catalog.Api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalogdb
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: Services/Catalog.API/Dockerfile
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    depends_on:
      - basketdb
    environment:
      - "CacheSettings:ConnectionString=basketdb:6379"
    ports: 
      - "5001:80"
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile

  usercard.api:
    image: ${DOCKER_REGISTRY-}usercardapi
    container_name: usercard.Api
    depends_on: 
      - usercarddb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"
    build:
      context: .
      dockerfile: Services/UserCard.API/Dockerfile
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  
  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    container_name: user.Api
    depends_on:
      - userdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5004:80"
    build:
      context: .
      dockerfile: Services/User.API/Dockerfile
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    container_name: ocelotapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - catalog.api
        - usercard.api
        - user.api
    ports:
     - "8010:80"
    build:
      context: .
      dockerfile: ApiGateway/OcelotAPIGateway/Dockerfile