# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  basket.api:
    build:
      context: "C:\\Users\\palvl\\source\\repos\\Cinema"
      dockerfile: "Services/Basket.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/Basket.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "basketapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\palvl\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\palvl\\source\\repos\\Cinema\\Services\\Basket.API:/app:rw"
    - "C:\\Users\\palvl\\source\\repos\\Cinema:/src:rw"
    working_dir: "/app"
  catalog.api:
    build:
      context: "C:\\Users\\palvl\\source\\repos\\Cinema"
      dockerfile: "Services/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/Catalog.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\palvl\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\palvl\\source\\repos\\Cinema\\Services\\Catalog.API:/app:rw"
    - "C:\\Users\\palvl\\source\\repos\\Cinema:/src:rw"
    working_dir: "/app"
  ocelotapigateway:
    build:
      context: "C:\\Users\\palvl\\source\\repos\\Cinema"
      dockerfile: "ApiGateway/OcelotAPIGateway/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/OcelotAPIGateway.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "ocelotapigateway:dev"
    ports: []
    volumes:
    - "C:\\Users\\palvl\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\palvl\\source\\repos\\Cinema\\ApiGateway\\OcelotAPIGateway:/app:rw"
    - "C:\\Users\\palvl\\source\\repos\\Cinema:/src:rw"
    working_dir: "/app"
  user.api:
    build:
      context: "C:\\Users\\palvl\\source\\repos\\Cinema"
      dockerfile: "Services/User.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/User.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "userapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\palvl\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\palvl\\source\\repos\\Cinema\\Services\\User.API:/app:rw"
    - "C:\\Users\\palvl\\source\\repos\\Cinema:/src:rw"
    working_dir: "/app"
  usercard.api:
    build:
      context: "C:\\Users\\palvl\\source\\repos\\Cinema"
      dockerfile: "Services/UserCard.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/UserCard.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "usercardapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\palvl\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\palvl\\source\\repos\\Cinema\\Services\\UserCard.API:/app:rw"
    - "C:\\Users\\palvl\\source\\repos\\Cinema:/src:rw"
    working_dir: "/app"
